<a href="https://colab.research.google.com/github/putrilestari434/PraktikumKecerdasanBuatan/blob/main/praktikum_6_kecerdasan_buatan_G_211_22_0001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!pip install keras
#Remove '#' in above line if not installed keras
import keras
import numpy as np
from sklearn.datasets import load_iris
dataset=load_iris()
##How data looks like?
print(dataset)


{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [ ]:
##Step  : 1 : Know the data
print(type(dataset))
print(len(dataset))
#Dataset is in bunch format. Bunch is a dictionary like object.
print(dataset.keys())
#We try to find out what values are stored in these attributes
print(dataset['data'][0:5])
print(dataset['target'][0:5])
print(dataset['target_names'][0:5])
print(dataset['DESCR'])
print(dataset['feature_names'])
print(dataset['filename'])
#Next we define our x and y; y is the dependent on x
x=dataset['data']
print(len(x)) #To check length of dataset
y=dataset['target']
print(len(y)) #To check length of targets
print(x[0])
print(y[0])


<class 'sklearn.utils._bunch.Bunch'>
8
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
['setosa' 'versicolor' 'virginica']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ==============

In [ ]:
##Step : 2 : Convert y into one hot encoded vector
#One hot encoding is used because Y has labels (0,1,2)- which is a categorical categorical data with no ordinal relationships
from keras.utils import to_categorical
Ny=len(np.unique(y))
print(Ny)
Y=to_categorical(y,num_classes=Ny)
print(Y[0:5])


3
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [ ]:
##Step : 3 : Now we split the data into two parts - one for training another for testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.10,shuffle=True)
print(x_train[0:5])
print(x_test[0:5])
print(y_train[0:5])
print(y_test[0:5])


[[5.6 2.5 3.9 1.1]
 [5.8 2.7 5.1 1.9]
 [4.9 2.4 3.3 1. ]
 [5.  2.3 3.3 1. ]
 [5.  2.  3.5 1. ]]
[[5.7 2.8 4.1 1.3]
 [5.6 3.  4.1 1.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.1 1.5 0.2]
 [6.3 2.8 5.1 1.5]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [ ]:
##Step : 4 : Then we normalize the data
from sklearn.preprocessing import StandardScaler
##Normalization is done so that the difference between highest and lowest data point is not too large
import numpy as np
scaler=StandardScaler()
##To find mean and std dev
scaler.fit(x_train)

##Converting data into form where mean of data  is 0 and std dev is 1
X_train=scaler.transform(x_train)
X_test=scaler.transform(x_test)
print(np.amax(X_train,axis=0))
print(np.amin(X_train,axis=0))


[2.41628261 3.13219669 1.74525683 1.66360651]
[-1.8978737  -2.44073976 -1.59953881 -1.47930025]


In [ ]:
##Step : 5 : Now finally we build the model using keras
!pip install tensorflow
import keras
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(20, input_dim=X_train.shape[1], activation='relu'))
##Dropout is used to avoid overfitting
keras.layers.Dropout(0.2)
model.add(Dense(20, activation='relu'))
keras.layers.Dropout(0.2)
model.add(Dense(20, activation='relu'))
keras.layers.Dropout(0.2)
##For classification problems, we usually use softmax  as activation function in final layer
model.add(Dense(3, activation='softmax'))
##Compiling the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])



In [ ]:
##Step : 6 : Know the model
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 20)                100       
                                                                 
 dense_1 (Dense)             (None, 20)                420       
                                                                 
 dense_2 (Dense)             (None, 20)                420       
                                                                 
 dense_3 (Dense)             (None, 3)                 63        
                                                                 
Total params: 1003 (3.92 KB)
Trainable params: 1003 (3.92 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
##Step : 7 : Train the model
##Batch size,epochs and validation split are all hyper parameters
model.fit(X_train, y_train, epochs=195, batch_size=80, validation_split=0.1)


Epoch 1/195
2/2 [==============================] - 1s 321ms/step - loss: 1.1139 - accuracy: 0.3471 - val_loss: 1.0765 - val_accuracy: 0.4286
Epoch 2/195
2/2 [==============================] - 0s 80ms/step - loss: 1.0964 - accuracy: 0.3719 - val_loss: 1.0593 - val_accuracy: 0.4286
Epoch 3/195
2/2 [==============================] - 0s 72ms/step - loss: 1.0806 - accuracy: 0.3719 - val_loss: 1.0442 - val_accuracy: 0.4286
Epoch 4/195
2/2 [==============================] - 0s 35ms/step - loss: 1.0651 - accuracy: 0.3884 - val_loss: 1.0304 - val_accuracy: 0.4286
Epoch 5/195
2/2 [==============================] - 0s 33ms/step - loss: 1.0510 - accuracy: 0.4050 - val_loss: 1.0172 - val_accuracy: 0.4286
Epoch 6/195
2/2 [==============================] - 0s 36ms/step - loss: 1.0371 - accuracy: 0.4215 - val_loss: 1.0043 - val_accuracy: 0.4286
Epoch 7/195
2/2 [==============================] - 0s 38ms/step - loss: 1.0236 - accuracy: 0.4380 - val_loss: 0.9928 - val_accuracy: 0.4286
Epoch 8/195
2/2 [==

In [ ]:
##Step ; 8 ; Get the accuaracy of model on testing data
testing=model.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1]+'uracy of Model on testing data', testing[1]*100))


1/1 [==============================] - 0s 40ms/step - loss: 0.4284 - accuracy: 0.8667

accuracyuracy of Model on testing data: 86.67%
